### PR TITLE
autopollservice always update cache at first poll

### LINKED ISSUE #43: With autopoll initial tryReadFromCache takes 5 seconds
### Describe the bug

We're using a toggle immediately after loading our application and noticed a 5 second delay of our application loading. After debugging the problem I noticed that although the configcat cdn replies within 30ms, the first `client.getValueAsync` still takes almost **5 seconds** (default config value for `maxInitWaitTimeSeconds`).

Our configuration: configcat-js v5.7.2 with AutoPoll:

```typescript
import { createClientWithAutoPoll, createConsoleLogger } from 'configcat-js'
const logger = createConsoleLogger(LogLevel.Off)
const client = createClientWithAutoPoll('our-key', {
    logger,
    pollIntervalSeconds: 300,
    requestTimeoutMs: 5000,
  })

const getValue =  <T>(featureName: string, defaultValue: T, context: any) => client.getValueAsync(featureName, defaultValue, context)
```

### Expected behavior

Since loading the config takes about 25ms and evaluation of most settings about 15ms I would expect a responsetime of approx 40ms.

### Cause of the issue:

- `AutoPollConfigService.tryReadFromCache` checks for timeStamp of the cache (line 85) and will keep waiting for a cache update until `maxInitWaitTimeStamp` has passed;
- `AutoPollConfigService.startRefreshWorker` calls `refreshLogic` with `forceUpdateCache = false` (line 64), therefore `ConfigServiceBase.refreshLogicBaseAsync` will not update the cache if the configuration hasn't changed since the last visit to our website. Since cache is persisted in localstorage it will still have the old timestamp.

### Suggested solution:

Code change in `AutoPollConfigService.ts` to force cache update on startup:

line 20:
```typescript
this.startRefreshWorker(autoPollConfig.pollIntervalSeconds * 1000, true);
```

`startRefreshWorker`:
```typescript
    private startRefreshWorker(delay: number, forceUpdateCache = false) {
        this.refreshLogic(forceUpdateCache).then((_) => {
            if (this.disposed) {
                return;
            }
            this.timerId = setTimeout(
                () => {
                    this.startRefreshWorker(delay);
                },
                delay);
        });
    }
```

### PR DESCRIPTION
**Pull request by endret**
### Describe the purpose of your pull request

AutoPollConfigService will always update the cache at the first poll with the latest `TimeStamp` value even if it does not change. The `GetConfig` method will only block while the fetch logic returns the result or for the time specified in the `maxInitWaitTimeSeconds` parameter (default: 5000 ms).

### Related issues (only if applicable)

https://github.com/configcat/common-js/issues/43

### Requirement checklist (only if applicable)

- [X] I have covered the applied changes with automated tests.
- [X] I have executed the full automated test set against my changes.
- [X] I have validated my changes against all supported platform versions.
- [X] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

### CODE REVIEW

File: test/ConfigServiceBaseTests.ts [hunk 1]
```diff
@@ -25,7 +26,7 @@ describe("ConfigServiceBaseTests", () => {
         ])
     };
 
-    it("AutoPollConfigService - backgroundworker only - config doesn't exits in the cache - invokes 'cache.set' operation only once", async () => {
+    it("AutoPollConfigService - backgroundworker only - config doesn't exit in the cache - invokes 'cache.set' operation only once", async () => {
```
Comment (sigewuzhere) [inline test/ConfigServiceBaseTests.ts]:
```suggestion
    it("AutoPollConfigService - backgroundworker only - config doesn't exist in the cache - invokes 'cache.set' operation only once", async () => {
```

File: test/ConfigServiceBaseTests.ts [hunk 2]
```diff
@@ -96,18 +97,22 @@ describe("ConfigServiceBaseTests", () => {
         cacheMock.verify(v => v.set(It.IsAny<string>(), pc), Times.Exactly(2));        
     });
 
-    it("AutoPollConfigService - ProjectConfig is cached and fetch returns same value - should never invokes 'cache.set' operation", async () => {
+    it("AutoPollConfigService - ProjectConfig is cached and fetch returns same value - should invokes 'cache.set' operation only once (at first)", async () => {
```
Comment (sigewuzhere) [inline test/ConfigServiceBaseTests.ts]:
```suggestion
    it("AutoPollConfigService - ProjectConfig is cached and fetch returns same value - should invoke the 'cache.set' operation only once (at first)", async () => {
```

File: test/ConfigServiceBaseTests.ts [hunk 3]
```diff
@@ -123,39 +128,150 @@ describe("ConfigServiceBaseTests", () => {
...
 
-        cacheMock.verify(v => v.set(It.IsAny<string>(), It.IsAny<ProjectConfig>()), Times.Never());        
+        cacheMock.verify(v => v.set(
+            It.IsAny<string>(),
+            It.Is<ProjectConfig>(actual => actual.Timestamp == projectConfigNew.Timestamp)),
+        Times.Once());     
     });
 
-    it("AutoPollConfigService - Async cache is supported", async () => {
+    it("AutoPollConfigService - ProjectConfigs are same but cache stores older config than poll interval - Should wait until cache update with new timestamp", async () => {
```
Comment (sigewuzhere) [inline test/ConfigServiceBaseTests.ts]:
```suggestion
    it("AutoPollConfigService - Cached config is the same as ProjectConfig but older than the polling time - Should wait until the cache is updated with the new timestamp", async () => {
```

File: test/ConfigServiceBaseTests.ts [hunk 4]
```diff
@@ -123,39 +128,150 @@ describe("ConfigServiceBaseTests", () => {
...
+
+        const actualProjectConfig: ProjectConfig | null = await service.getConfig();
+
+        // Assert
+
+        assert.isNotNull(actualProjectConfig);
+        assert.equal(actualProjectConfig?.Timestamp, projectConfigNew.Timestamp);
+    });
+
+    it("AutoPollConfigService - ProjectConfigs are same but cache stores not older config than poll interval - Should return cached item", async () => {
```
Comment (sigewuzhere) [inline test/ConfigServiceBaseTests.ts]:
```suggestion
    it("AutoPollConfigService - Cached config is the same as ProjectConfig but older than the polling time - Should return cached item", async () => {
```

**Review by sigewuzhere — CHANGES_REQUESTED** [review]

**Review by sigewuzhere — APPROVED** [review]

**Review by laliconfigcat — APPROVED** [review]
